# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
appVersion: "2.0.0"
description:  Helm chart for Open Cluster Management console UI
name: console-chart
version: 2.0.0
category: "Development"
tillerVersion: ">=2.9.1"
kubeVersion: ">=1.10.0-0"
keywords:
  - ui
