# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

# Copyright IBM, Red Hat, and collected contributors to the OCM project
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:aggregate-clusterimagesets-readonly
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterimagesets"]
  verbs: ["get", "list", "watch"]
