# Copyright (c) 2020 Red Hat, Inc.
# Copyright IBM, Red Hat, and collected contributors to the OCM project

apiVersion: v1
kind: Service
metadata:
  name: console-header
  labels:
    app: console-header
    component: "console-header"
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: console-header
    component: "console-header"
    release: {{ .Release.Name }}
