apiVersion: v1
kind: Secret
metadata:
  name: {{ template "console.fullname" . }}-console-new
  labels:
    app: {{ template "console.name" . }}-new
    component: "console"
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "console.fullname" . }}
type: kubernetes.io/service-account-token