# Copyright (c) 2020 Red Hat, Inc.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "console.fullname" . }}-console-header
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    component: "consoleheader"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
<<<<<<< 00dcb36a821bfa182dffe8d15d13294228c27215:stable/console-chart/templates/console-header-deployment.yaml
      k8s-app: console-header
      app: console-header
      component: "console-header"
=======
      app: {{ template "console.name" . }}
      component: "consoleheader"
      release: {{ .Release.Name }}
  minReadySeconds: 0
>>>>>>> Update console-header to run as Deployment:stable/console-chart/templates/console-header-deployment.yaml
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "console.name" . }}
        component: "consoleheader"
        release: {{ .Release.Name }}
        chart: {{ template "console.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "console.name" . }}
        helm.sh/chart: {{ template "console.chart" . }}
      annotations:
        productName: "Open Cluster Management - Server"
        productVersion: "1.0.0"
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - mcm-controller
              topologyKey: failure-domain.beta.kubernetes.io/zone
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
      volumes:
      - name: log4js
        configMap:
          name: {{ template "console.fullname" . }}-console-header-log4js
          items:
          - key: log4js.json
            path: log4js.json
      - name: cluster-ca
        secret:
          defaultMode: 420
          items:
          - key: tls.key
            path: ca.key
          - key: tls.crt
            path: ca.crt
          secretName: multicloud-ca-cert
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
        - name: console-header
          image: "{{ .Values.consoleheader.image.repository}}:{{ .Values.consoleheader.image.tag }}{{ .Values.imageTagPostfix }}"
          resources:
{{ toYaml .Values.consoleheader.resources | indent 12 }}
          imagePullPolicy: {{ .Values.consoleheader.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 30
          volumeMounts:
          - name: log4js
            mountPath: /etc/config
          - mountPath: /opt/app-root/console-header/certs
            name: cluster-ca
          env:
            - name: headerContextPath
              value: {{ .Values.consoleheader.ingressPath}}
            - name: headerUrl
              value: {{ .Values.cfcRouterUrl }}
            - name: NODE_EXTRA_CA_CERTS
              value: /opt/app-root/console-header/certs/ca.crt
            - name: NAV_PORT
              value: "{{ .Values.navPort }}"
            - name: default_admin_user
              value: admin
            - name: SESSION_POLLING_INTERVAL
              value: "300"
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
