# Copyright (c) 2020 Red Hat, Inc.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-open-cluster-management
    ingress.open-cluster-management.io/app-root: /multicloud/welcome
    ingress.open-cluster-management.io/auth-type: access-token
  name: console-header
  labels:
    app: console-header
    component: "console-header"
    release: {{ .Release.Name }}
    heritage: {{.Release.Service | quote }}
    chart: {{ template "console.chart" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: console-header
          servicePort: 3000
        path: /multicloud/header/
