# Copyright (c) 2020 Red Hat, Inc.
# Copyright IBM, Red Hat, and collected contributors to the OCM project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:clusterrole
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
    component: clusterrole
rules:
- apiGroups:
  - 'authentication.k8s.io'
  resources:
  - 'tokenreviews'
  verbs:
  - create
- apiGroups:
  - 'operator.open-cluster-management.io'
  resources:
  - 'multiclusterhubs'
  verbs:
  - get
- apiGroups:
  - 'config.openshift.io'
  - 'console.openshift.io'
  - 'project.openshift.io'
  resources:
  - 'infrastructures'
  - 'consolelinks'
  - 'projects'
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - 'services'
  verbs:
  - list
