# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "console.fullname" . }}-console-new
  labels:
    app: {{ template "console.name" . }}-new
    component: "console"
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "console.name" . }}-new
    component: "console"
    release: {{ .Release.Name }}
