# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.
{{- if .Values.global.imageOverrides.console }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "console.fullname" . }}-console-new
  labels:
    app: {{ template "console.name" . }}-new
    chart: {{ template "console.chart" . }}
    component: "console"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "console.name" . }}-new
      component: "console"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "console.name" . }}-new
        component: "console"
        release: {{ .Release.Name }}
        chart: {{ template "console.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "console.name" . }}
        helm.sh/chart: {{ template "console.chart" . }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "console.fullname" . }}
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "console.name" . }}
                - key: component
                  operator: In
                  values:
                  - console
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "console.name" . }}
                - key: component
                  operator: In
                  values:
                  - console
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: console
        image: {{ .Values.global.imageOverrides.console }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        resources:
        {{- toYaml .Values.console.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: PORT
          value: "3000"
        - name: searchApiUrl
          value: https://search-search-api:4010/searchapi
        - name: CLUSTER_API_URL
          value: https://kubernetes.default.svc:443
        - name: FRONTEND_URL
          value: "https://multicloud-console.{{ .Values.ocpingress }}/cluster-management/"
        - name: BACKEND_URL
          value: "https://multicloud-console.{{ .Values.ocpingress }}/cluster-management/"
        - name: OAUTH2_REDIRECT_URL
          value: https://multicloud-console.{{ .Values.ocpingress }}/cluster-management/login/callback
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
