# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:clusterrole
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
    component: clusterrole

rules:

- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create

- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - get

- apiGroups:
  - config.openshift.io
  - console.openshift.io
  - project.openshift.io
  resources:
  - infrastructures
  - consolelinks
  - projects
  - featuregates
  verbs:
  - list
  - get
  - watch

- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - list

- verbs:
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  - jobs
  - namespaces
  - pods
  - secrets

- verbs:
  - watch
  apiGroups:
  - inventory.open-cluster-management.io
  resources:
  - baremetalassets

- verbs:
  - watch
  apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests

- verbs:
  - watch
  apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - clusterpools
  - clusterimagesets
  - clusterprovisions
  - clusterdeprovisions
  - machinepools

- verbs:
  - watch
  apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  - managedclusteraddons

- verbs:
  - watch
  apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclustersets

- verbs:
  - watch
  apiGroups:
  - internal.open-cluster-management.io
  resources:
  - managedclusterinfos

- verbs:
  - watch
  apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs
  - discoveredclusters

- verbs:
  - watch
  apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports