# Copyright (c) 2020 Red Hat, Inc.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    kubernetes.io/ingress.class: ingress-open-cluster-management
    ingress.open-cluster-management.io/rewrite-target: /  
  name: {{ template "console.fullname" . }}-console-v2
  labels:
    app: {{ template "console.name" . }}-v2
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ template "console.fullname" . }}-console-v2
          servicePort: 3000
        path: /cluster-management
