# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "console.fullname" . }}-console-header-config
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    component: "consoleheaderconfig"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
data:
  ui-config.json: |-
    {
      "icpText": "{{ .Values.consoleheader.uiconfig.icpText }}",
      "about": {
        "path": "{{ .Values.consoleheader.uiconfig.about.text }}"
      },
      "header": {
        "path": "{{ .Values.consoleheader.uiconfig.header.path }}",
        "width": "{{ .Values.consoleheader.uiconfig.header.width }}",
        "height": "{{ .Values.consoleheader.uiconfig.header.height }}"
      }
    }
