apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.6.22-x86-64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.6.22-x86_64
