apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.3.40-x86-64-chart
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.3.40-x86_64
